[tool.poetry]
name = "bean-fetch"
version = "0.1.0"
description = ""
authors = ["David Terry <me@xwvvvvwx.com>"]

[tool.poetry.dependencies]
python = "^3.7"
beancount = "^2.2"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
